from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class CandidateTask(BaseModel):
    """
    Represents a proposed task step in an uncompiled CandidatePlan.
    """
    task_id: str = Field(..., description="Unique task identifier within the candidate plan.")
    objective: str = Field(..., description="Explicit, non-empty objective or instruction for the agent.")
    agent_id: str = Field(..., description="Target agent identifier.")
    operation: str = Field(..., description="Requested operation name.")
    inputs: Optional[Dict[str, Any]] = Field(default=None, description="Structured inputs and tool parameters.")
    dependencies: List[str] = Field(default_factory=list, description="Preceding task IDs upon which this task depends.")
    rationale: Optional[str] = Field(default=None, description="Explanation or reasoning provided by the LLM planner.")

class CandidatePlan(BaseModel):
    """
    Represents the intermediate, probabilistic execution plan generated by the LLM Planner.
    """
    plan_id: str = Field(..., description="Unique identifier for the planning session.")
    intent: str = Field(..., description="Original natural language user intent or goal.")
    target_model: str = Field(..., description="LLM identifier used for generation.")
    tasks: List[CandidateTask] = Field(default_factory=list, description="Ordered list of candidate task steps.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional planning metadata and provenance.")
